// Generated by CoffeeScript 1.4.0
(function() {
  var TMAC;

  TMAC = (function() {

    function TMAC() {
      if (!((typeof pagenow !== "undefined" && pagenow !== null) && pagenow === "settings_page_tmac_options")) {
        return;
      }
      jQuery("#cron-details").siblings("input").click(this.toggleCron);
      if (twitter_mentions_as_comments.hide_manual_cron_details) {
        jQuery("#cron-details").hide();
      }
    }

    TMAC.prototype.toggleCron = function() {
      if (jQuery(this).val() === "1") {
        return jQuery("#cron-details").slideDown();
      } else {
        return jQuery("#cron-details").slideUp();
      }
    };

    return TMAC;

  })();

  jQuery(document).ready(function() {
    return window.tmac = new TMAC();
  });

}).call(this);
